### ISSUE TITLE
Need help displaying initial response

### ISSUE THREAD

**Issue by Mishel-T** [Mishel-T/travelRush#5]
Need some help displaying results on initial submit. In the following snippet, I've captured the on click event of the submit button and run a yelp api query for each of the three relevant search terms. Now that I've successfully run all 3 yelp api calls simultaneously on click, I'm trying to figure out how to take the results from each respective div to display them to the cards. I'm currently trying out an if/else function, but I can't get the function to distinguish from each of the responses. I would greatly appreciate it if someone had time to take a look and see if you have any suggestions. I'm going to keep trying tonight to hopefully have this resolved by tomorrow's set up meeting. (The full code is uploaded to my branch phase3-MT)
Thanks!
var searchTerm = ["hotels", "restaurants","coffee"];

   for (var i=0; i<searchTerm.length; i++) {
       console.log(searchTerm[i])
   var yelpAPIKey = "NNn_iZkgwcsoXyb1LwNcwgRAiCL8c3RkazAkRcQueV0e5b0lZNV-SGGIeosL3AiABzN0_PsQasfbyA8BkbNTjHr-RiTH3sKFAPyB8SCmQInth1SBzlW1uhiuBsr5XHYx"

   var yelpURL = "https://cors-anywhere.herokuapp.com/https://api.yelp.com/v3/businesses/search?term=" + searchTerm[i] + "&location=boston&limit=10";

   $.ajax({
       url: yelpURL,
       headers: {
       'Authorization': 'Bearer ' + yelpAPIKey,
       },
   method: 'GET',
   dataType: 'json',
   success: function (data) {
       console.log('success: ' + data);
   }
   }).then(function (response) {
       console.log(response);
    //store 0 index search results parameters in variables to then push to each card
    //if else functions to state if index of 0 1 or 2 post to specific places
    if (searchTerm[i]==="hotels") {

        var alias = response.businesses[0].alias
        console.log(alias)
    }

   });
//push 0 index of each result to card - to do that, store all parameters in variables after ajax call
}
})

**Comment by martinezg52** [comment]
Just saw this, were you able to figure it out? I see you closed it.

**Comment by Mishel-T** [comment]
I was! Thanks GeoSent from my T-Mobile 4G LTE Device
-------- Original message --------From: martinezg52 <notifications@github.com> Date: 6/10/19  12:17 AM  (GMT-08:00) To: Mishel-T/travelRush <travelRush@noreply.github.com> Cc: Mishel-T <mishelt13@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [Mishel-T/travelRush] Need help displaying initial response (#5) Just saw this, were you able to figure it out? I see you closed it.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Mishel-T/travelRush/issues/5?email_source=notifications\u0026email_token=ALWH6YWIQWVFPXMY5RAZTRDPZX5ZRA5CNFSM4HWQEPV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJD2EI#issuecomment-500317457",
"url": "https://github.com/Mishel-T/travelRush/issues/5?email_source=notifications\u0026email_token=ALWH6YWIQWVFPXMY5RAZTRDPZX5ZRA5CNFSM4HWQEPV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJD2EI#issuecomment-500317457",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
